import React, { createContext, useContext, useState, useEffect } from 'react';
import { Alert, I18nManager } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Language = 'en' | 'ar';
type TranslationVars = Record<string, string | number | null | undefined>;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, vars?: TranslationVars) => string;
  isRTL: boolean;
}

const STORAGE_KEY = 'privara_language';

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Auth
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.full_name': 'Full Name',
    'auth.signin_title': 'Sign in to your account',
    'auth.signin_button': 'Sign In',
    'auth.login_subtitle': 'Secure consultation management',
    'auth.register_title': 'Create your account',
    'auth.register_subtitle': 'Start your real estate consultation journey',
    'auth.register_button': 'Create Account',
    'auth.email_placeholder': 'you@example.com',
    'auth.password_placeholder': '••••••••',
    'auth.full_name_placeholder': 'John Doe',
    'auth.new_to': 'New to Privara Estate?',
    'auth.create_account': 'Create an Account',
    'auth.already_have': 'Already have an account?',
    'auth.signin_instead': 'Sign In Instead',
    'auth.agree_to': 'I agree to the',
    'auth.terms': 'Terms of Service',
    'auth.and': 'and',
    'auth.privacy': 'Privacy Policy',
    'auth.account_deactivated': 'Your account has been deactivated. Please contact support.',

    // Login errors
    'auth.login.error.invalid_credentials': 'Invalid email or password.',
    'auth.login.error.invalid_email': 'Please enter a valid email address.',
    'auth.login.error.too_many_requests': 'Too many attempts. Please try again later.',
    'auth.login.error.operation_not_allowed': 'Email login is not enabled.',
    'auth.login.error.generic': 'An error occurred. Please try again.',
    'auth.login.error.profile_missing': 'Account profile not found. Please contact support.',
    'auth.login.success': 'Signed in successfully!',

    // Register errors
    'auth.register.error.email_in_use': 'This email is already registered.',
    'auth.register.error.invalid_email': 'Please enter a valid email address.',
    'auth.register.error.weak_password': 'Password must be at least 6 characters.',
    'auth.register.error.operation_not_allowed': 'Registration is not enabled.',
    'auth.register.error.generic': 'Registration failed. Please try again.',
    'auth.register.error.profile_sync_failed': 'Account created but profile sync failed. Please contact support.',

    // Verify email
    'auth.verify_email.title': 'Verify your email',
    'auth.verify_email.subtitle': 'We sent a verification link to your email address.',
    'auth.verify_email.sent': 'Verification email sent. Check your inbox.',
    'auth.verify_email.sent_to': 'Verification sent to',
    'auth.verify_email.resend': 'Resend Email',
    'auth.verify_email.resend_success': 'Verification email sent!',
    'auth.verify_email.resend_error': 'Failed to send verification email.',
    'auth.verify_email.ive_verified': "I've Verified",
    'auth.verify_email.checking': 'Checking...',
    'auth.verify_email.not_verified_yet': 'Email not verified yet. Please check your inbox.',
    'auth.verify_email.cooldown': 'Wait {seconds}s',
    'auth.verify_email.use_different': 'Use a different account',
    'auth.verify_email.required': 'Please verify your email first.',

    // Forgot password
    'auth.forgotPassword.title': 'Reset Password',
    'auth.forgotPassword.subtitle': "Enter your email and we'll send a reset link.",
    'auth.forgotPassword.submit': 'Send Reset Link',
    'auth.forgotPassword.success': 'If an account exists, a reset email was sent.',
    'auth.forgotPassword.link': 'Forgot password?',
    'auth.forgotPassword.email_placeholder': 'Enter your email',
    'auth.forgotPassword.error.invalid_email': 'Please enter a valid email.',
    'auth.forgotPassword.error.too_many_requests': 'Too many attempts. Try again later.',
    'auth.forgotPassword.error.generic': 'Something went wrong. Try again.',

    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.cases': 'Cases',
    'nav.profile': 'Profile',
    'nav.support': 'Support',
    'nav.staff': 'Staff',
    'nav.clients': 'Clients',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    'nav.logout': 'Sign Out',

    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.active': 'Active',
    'common.completed': 'Completed',
    'common.pending': 'Pending',
    'common.status': 'Status',
    'common.empty': 'No items found',
    'common.error': 'Something went wrong',
    'common.retry': 'Retry',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.yes': 'Yes',
    'common.no': 'No',

    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.active_cases': 'Active Cases',
    'dashboard.completed_cases': 'Completed Cases',
    'dashboard.total_cases': 'Total Cases',
    'dashboard.unassigned': 'Unassigned',
    'dashboard.total_staff': 'Total Staff',
    'dashboard.avg_rating': 'Avg. Rating',
    'dashboard.no_cases': 'No cases yet',
    'dashboard.start_consultation': 'Start a Consultation',

    // Cases
    'case.status.new': 'New',
    'case.status.assigned': 'Assigned',
    'case.status.active': 'Active',
    'case.status.waiting_for_client': 'Waiting for Client',
    'case.status.waiting_for_consultant': 'Waiting for Consultant',
    'case.status.report_sent': 'Report Sent',
    'case.status.completed': 'Completed',
    'case.status.reassigned': 'Reassigned',
    'case.stage.intake': 'Intake',
    'case.stage.need_analysis': 'Need Analysis',
    'case.stage.shortlisting': 'Shortlisting',
    'case.stage.comparison': 'Comparison',
    'case.stage.meeting': 'Meeting',
    'case.stage.final_recommendation': 'Final Recommendation',
    'case.stage.closure': 'Closure',
    'case.case_number': 'Case',
    'case.view_details': 'View Details',
    'case.chat': 'Chat',
    'case.consultant': 'Consultant',
    'case.no_consultant': 'Not yet assigned',
    'case.goal': 'Goal',
    'case.preferred_area': 'Preferred Area',
    'case.budget_range': 'Budget Range',
    'case.property_type': 'Property Type',
    'case.delivery_time': 'Delivery Time',
    'case.notes': 'Notes',
    'case.projects_in_mind': 'Projects in Mind',
    'case.intake_info': 'Intake Information',
    'case.report': 'Report',
    'case.report_pending': 'Report pending',
    'case.download_report': 'Download Report',
    'case.internal_notes': 'Internal Notes',
    'case.tags': 'Tags',
    'case.rate': 'Rate',
    'case.rating': 'Rating',
    'case.feedback': 'Feedback',
    'case.submit_rating': 'Submit Rating',
    'case.request_change': 'Request Consultant Change',
    'case.change_reason': 'Reason for change',
    'case.change_hint': 'Not satisfied with your consultant? You can request a change.',
    'case.change_reason_hint': 'Please explain why you would like a different consultant.',
    'case.change_pending': 'Pending',
    'case.change_pending_hint': 'Your request is being reviewed by our team.',
    'case.change_request_submitted': 'Your consultant change request has been submitted.',
    'case.reason_required': 'Please provide a reason for the change request.',
    'case.rate_placeholder': 'Share your experience with this consultation…',
    'case.rating_required': 'Please select a star rating before submitting.',
    'case.thank_you_rating': 'Thank you for your feedback!',
    'case.mark_completed': 'Mark Completed',
    'case.upload_report': 'Upload Report',
    'case.upload_recording': 'Upload Meeting Recording',
    'case.update_status': 'Update Status',
    'case.update_stage': 'Update Stage',

    // Intake form
    'intake.title': 'New Consultation',
    'intake.goal_label': 'Goal',
    'intake.goal.living': 'Living',
    'intake.goal.investment': 'Investment',
    'intake.goal.resale': 'Resale',
    'intake.preferred_area': 'Preferred Area',
    'intake.budget_range': 'Budget Range',
    'intake.property_type': 'Property Type',
    'intake.delivery_time': 'Preferred Delivery Time',
    'intake.projects': 'Projects in Mind (optional)',
    'intake.notes': 'Additional Notes',
    'intake.select_consultant': 'Select a Consultant (optional)',
    'intake.assign_later': 'Admin will assign later',
    'intake.proceed_to_payment': 'Proceed to Payment',

    // Payment
    'payment.title': 'Payment',
    'payment.fee': 'Consultation Fee',
    'payment.secure': 'Secure payment via Geidea',
    'payment.pay_now': 'Pay Now',
    'payment.success': 'Payment successful!',
    'payment.failed': 'Payment failed. Please try again.',
    'payment.checking': 'Verifying payment, please wait…',
    'payment.timeout': 'Could not confirm payment. Did you complete the payment?',
    'payment.check_again': "I've Paid — Check Again",
    'payment.cancel': 'Cancel Payment',

    // Support
    'support.title': 'Support',
    'support.new_ticket': 'New Ticket',
    'support.subject': 'Subject',
    'support.message': 'Message',
    'support.send': 'Send',
    'support.no_tickets': 'No support tickets',
    'support.reply': 'Reply',
    'support.close_ticket': 'Close Ticket',
    'support.status.open': 'Open',
    'support.status.closed': 'Closed',
    'support.status.resolved': 'Resolved',

    // Profile
    'profile.title': 'Profile',
    'profile.display_name': 'Display Name',
    'profile.phone': 'Phone Number',
    'profile.location': 'Location',
    'profile.save_changes': 'Save Changes',
    'profile.saved': 'Profile updated!',
    'profile.language': 'Language',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.empty': 'No notifications',
    'notifications.mark_read': 'Mark as read',

    // Admin
    'admin.staff.title': 'Staff Management',
    'admin.staff.add': 'Add Staff',
    'admin.clients.title': 'Client Management',
    'admin.assign_consultant': 'Assign Consultant',
    'admin.assign_quality': 'Assign Quality Specialist',
    'admin.reassign_consultant': 'Reassign Consultant',
    'admin.reassign_quality': 'Reassign Quality Specialist',
    'admin.select_consultant': 'Select Consultant',
    'admin.select_quality': 'Select Quality Specialist',
    'admin.pending_reassignment': 'Pending Reassignment Request',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.reassignment_rejected': 'Reassignment request rejected.',
    'admin.settings': 'Settings',
    'admin.consultation_fee': 'Consultation Fee',
    'admin.export': 'Export CSV',
    'admin.mark_paid': 'Mark as Paid',
    'admin.mark_paid_confirm': 'Mark this case as paid? This cannot be undone.',
    'admin.participants': 'Participants',
    'admin.client': 'Client',
    'admin.requested_consultant': 'Requested Consultant',
    'admin.none': 'None',
    'admin.timeline': 'Activity Timeline',
    'admin.timeline_case_created': 'Case created',
    'admin.timeline_payment_paid': 'Payment received',
    'admin.timeline_payment_pending': 'Payment pending',
    'admin.timeline_consultant_assigned': 'Consultant assigned',
    'admin.timeline_quality_assigned': 'Quality specialist assigned',
    'admin.overview': 'Overview',
    'admin.conversations': 'Conversations',
    'admin.quality_reports': 'Quality Reports',
    'admin.support': 'Support',
    'admin.unassigned_cases': 'Unassigned Cases',
    'admin.active_cases': 'Active Cases',
    'admin.no_unassigned': 'No unassigned cases',
    'admin.no_active': 'No active cases',
    'admin.staff_load': 'Staff Load',
    'admin.active_count': '{count} active',
    'admin.monitor': 'Monitor',
    'admin.deactivate': 'Deactivate',
    'admin.activate': 'Activate',
    'admin.deactivate_confirm': 'Deactivate {name}? They will not be able to log in.',
    'admin.activate_confirm': 'Activate {name}? They will be able to log in again.',
    'admin.cannot_deactivate': 'Cannot deactivate: staff member has active cases. Reassign them first.',
    'admin.staff_detail': 'Staff Details',
    'admin.cases_assigned': 'Assigned Cases',
    'admin.no_cases_assigned': 'No cases assigned',
    'admin.fee_updated': 'Fee updated successfully.',
    // Clients
    'admin.clients.total': 'Total Clients',
    'admin.clients.with_consultations': 'With Consultations',
    'admin.clients.without_consultations': 'Without Consultations',
    'admin.clients.filter_all': 'All',
    'admin.clients.filter_with': 'With Consultations',
    'admin.clients.filter_without': 'Without Consultations',
    'admin.clients.deactivated': 'Deactivated',
    'admin.clients.active_count': 'Active',
    'admin.clients.completed_count': 'Completed',
    // Staff
    'admin.staff.filter_all': 'All Roles',
    'admin.staff.experience': 'Experience',
    'admin.staff.years_exp': 'yrs exp',
    'admin.staff.total_consultations': 'Total',
    'admin.staff.active_consultations': 'Active',
    'admin.staff.cases_in_progress': 'Cases in Progress',
    'admin.staff.reassign': 'Reassign',
    'admin.staff.reassigning': 'Reassigning…',
    'admin.staff.no_active_cases': 'No active cases',
    // Support (admin workspace)
    'admin.support.select_ticket': 'Select a ticket to view',
    'admin.support.reply': 'Reply',
    'admin.support.close_ticket': 'Close Ticket',
    'admin.support.ticket_closed': 'This ticket is closed.',
    'admin.support.send': 'Send',
    'admin.support.type_reply': 'Type your reply…',
    'admin.support.close_confirm': 'Close this support ticket?',
    'admin.support.closed_by': 'Closed',
    // Export
    'admin.export_consultations': 'Export Consultations',
    'admin.export_staff': 'Export Staff',
    'admin.export_quality': 'Export Quality Reports',
    'admin.export_empty': 'No data to export.',
    'admin.export_title': 'Export Reports',
    // Case detail
    'case.view_chat': 'View Chat History',

    // Quality
    'quality.audit': 'Quality Audit',
    'quality.classification': 'Classification',
    'quality.meeting_status': 'Meeting Status',
    'quality.submit_audit': 'Submit Audit Report',
    'quality.critical': 'Critical',
    'quality.non_critical': 'Non-Critical',
    'quality.recorded': 'Recorded',
    'quality.not_recorded': 'Not Recorded',
    'quality.failed': 'Failed',
    'quality.audit_notes': 'Audit Notes',
    'quality.notes_placeholder': 'Describe quality observations, issues found, and recommendations…',
    'quality.notes_required': 'Please add audit notes before submitting.',
    'quality.previous_reports': 'Audit Reports',
    'quality.no_reports': 'No audit reports yet',
    'quality.report_submitted': 'Audit report submitted successfully.',

    // Consultant
    'consultant.experience': 'Years of Experience',
    'consultant.specialties': 'Specialties',
    'consultant.completed': 'Completed Consultations',
    'consultant.bio': 'Bio',
    'consultant.summary': 'Professional Summary',
  },
  ar: {
    // Auth
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.full_name': 'الاسم الكامل',
    'auth.signin_title': 'تسجيل الدخول',
    'auth.signin_button': 'تسجيل الدخول',
    'auth.login_subtitle': 'إدارة الاستشارات الآمنة',
    'auth.register_title': 'إنشاء حساب',
    'auth.register_subtitle': 'ابدأ رحلة استشارتك العقارية',
    'auth.register_button': 'إنشاء حساب',
    'auth.email_placeholder': 'you@example.com',
    'auth.password_placeholder': '••••••••',
    'auth.full_name_placeholder': 'الاسم الكامل',
    'auth.new_to': 'جديد في بريفارا إستيت؟',
    'auth.create_account': 'إنشاء حساب',
    'auth.already_have': 'لديك حساب بالفعل؟',
    'auth.signin_instead': 'تسجيل الدخول',
    'auth.agree_to': 'أوافق على',
    'auth.terms': 'شروط الخدمة',
    'auth.and': 'و',
    'auth.privacy': 'سياسة الخصوصية',
    'auth.account_deactivated': 'تم تعطيل حسابك. يرجى الاتصال بالدعم.',

    'auth.login.error.invalid_credentials': 'بريد إلكتروني أو كلمة مرور غير صالحة.',
    'auth.login.error.invalid_email': 'يرجى إدخال بريد إلكتروني صالح.',
    'auth.login.error.too_many_requests': 'محاولات كثيرة جداً. حاول لاحقاً.',
    'auth.login.error.operation_not_allowed': 'تسجيل الدخول بالبريد غير مفعل.',
    'auth.login.error.generic': 'حدث خطأ. حاول مرة أخرى.',
    'auth.login.error.profile_missing': 'لم يتم العثور على الملف الشخصي.',
    'auth.login.success': 'تم تسجيل الدخول!',

    'auth.register.error.email_in_use': 'هذا البريد مسجل بالفعل.',
    'auth.register.error.invalid_email': 'بريد إلكتروني غير صالح.',
    'auth.register.error.weak_password': 'كلمة المرور ضعيفة (6 أحرف على الأقل).',
    'auth.register.error.operation_not_allowed': 'التسجيل غير مفعل.',
    'auth.register.error.generic': 'فشل التسجيل. حاول مرة أخرى.',
    'auth.register.error.profile_sync_failed': 'تم إنشاء الحساب لكن فشل مزامنة الملف الشخصي.',

    'auth.verify_email.title': 'تحقق من بريدك الإلكتروني',
    'auth.verify_email.subtitle': 'أرسلنا رابط تحقق إلى بريدك الإلكتروني.',
    'auth.verify_email.sent': 'تم إرسال بريد التحقق.',
    'auth.verify_email.sent_to': 'تم إرسال التحقق إلى',
    'auth.verify_email.resend': 'إعادة إرسال',
    'auth.verify_email.resend_success': 'تم إرسال بريد التحقق!',
    'auth.verify_email.resend_error': 'فشل إرسال بريد التحقق.',
    'auth.verify_email.ive_verified': 'لقد تحققت',
    'auth.verify_email.checking': 'جارٍ التحقق...',
    'auth.verify_email.not_verified_yet': 'لم يتم التحقق بعد.',
    'auth.verify_email.cooldown': 'انتظر {seconds}ث',
    'auth.verify_email.use_different': 'استخدام حساب مختلف',
    'auth.verify_email.required': 'يرجى التحقق من بريدك أولاً.',

    'auth.forgotPassword.title': 'إعادة تعيين كلمة المرور',
    'auth.forgotPassword.subtitle': 'أدخل بريدك وسنرسل رابط إعادة التعيين.',
    'auth.forgotPassword.submit': 'إرسال رابط',
    'auth.forgotPassword.success': 'إذا كان الحساب موجوداً، تم إرسال رابط.',
    'auth.forgotPassword.link': 'نسيت كلمة المرور؟',
    'auth.forgotPassword.email_placeholder': 'أدخل بريدك الإلكتروني',
    'auth.forgotPassword.error.invalid_email': 'بريد إلكتروني غير صالح.',
    'auth.forgotPassword.error.too_many_requests': 'محاولات كثيرة. حاول لاحقاً.',
    'auth.forgotPassword.error.generic': 'حدث خطأ. حاول مرة أخرى.',

    'nav.home': 'الرئيسية',
    'nav.dashboard': 'لوحة التحكم',
    'nav.cases': 'القضايا',
    'nav.profile': 'الملف الشخصي',
    'nav.support': 'الدعم',
    'nav.staff': 'الموظفون',
    'nav.clients': 'العملاء',
    'nav.notifications': 'الإشعارات',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',

    'common.loading': 'جارٍ التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.back': 'رجوع',
    'common.submit': 'إرسال',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.all': 'الكل',
    'common.active': 'نشط',
    'common.completed': 'مكتمل',
    'common.pending': 'معلق',
    'common.status': 'الحالة',
    'common.empty': 'لا توجد عناصر',
    'common.error': 'حدث خطأ',
    'common.retry': 'إعادة المحاولة',
    'common.confirm': 'تأكيد',
    'common.close': 'إغلاق',
    'common.open': 'فتح',
    'common.yes': 'نعم',
    'common.no': 'لا',

    'dashboard.welcome': 'مرحباً',
    'dashboard.active_cases': 'القضايا النشطة',
    'dashboard.completed_cases': 'القضايا المكتملة',
    'dashboard.total_cases': 'إجمالي القضايا',
    'dashboard.unassigned': 'غير معيّنة',
    'dashboard.total_staff': 'إجمالي الموظفين',
    'dashboard.avg_rating': 'متوسط التقييم',
    'dashboard.no_cases': 'لا توجد قضايا بعد',
    'dashboard.start_consultation': 'ابدأ استشارة',

    'case.status.new': 'جديد',
    'case.status.assigned': 'معيّن',
    'case.status.active': 'نشط',
    'case.status.waiting_for_client': 'بانتظار العميل',
    'case.status.waiting_for_consultant': 'بانتظار المستشار',
    'case.status.report_sent': 'تم إرسال التقرير',
    'case.status.completed': 'مكتمل',
    'case.status.reassigned': 'أُعيد تعيينه',
    'case.stage.intake': 'استقبال',
    'case.stage.need_analysis': 'تحليل الاحتياجات',
    'case.stage.shortlisting': 'القائمة المختصرة',
    'case.stage.comparison': 'المقارنة',
    'case.stage.meeting': 'اجتماع',
    'case.stage.final_recommendation': 'التوصية النهائية',
    'case.stage.closure': 'إغلاق',
    'case.case_number': 'قضية',
    'case.view_details': 'عرض التفاصيل',
    'case.chat': 'محادثة',
    'case.consultant': 'المستشار',
    'case.no_consultant': 'لم يتم التعيين بعد',
    'case.goal': 'الهدف',
    'case.preferred_area': 'المنطقة المفضلة',
    'case.budget_range': 'نطاق الميزانية',
    'case.property_type': 'نوع العقار',
    'case.delivery_time': 'وقت التسليم',
    'case.notes': 'ملاحظات',
    'case.projects_in_mind': 'مشاريع في البال',
    'case.intake_info': 'معلومات الاستقبال',
    'case.report': 'التقرير',
    'case.report_pending': 'التقرير قيد الانتظار',
    'case.download_report': 'تحميل التقرير',
    'case.internal_notes': 'ملاحظات داخلية',
    'case.tags': 'علامات',
    'case.rate': 'تقييم',
    'case.rating': 'التقييم',
    'case.feedback': 'ملاحظات',
    'case.submit_rating': 'إرسال التقييم',
    'case.request_change': 'طلب تغيير المستشار',
    'case.change_reason': 'سبب التغيير',
    'case.change_hint': 'غير راضٍ عن مستشارك؟ يمكنك طلب تغييره.',
    'case.change_reason_hint': 'يرجى توضيح سبب رغبتك في تغيير المستشار.',
    'case.change_pending': 'معلق',
    'case.change_pending_hint': 'طلبك قيد المراجعة من قِبل الفريق.',
    'case.change_request_submitted': 'تم تقديم طلب تغيير المستشار.',
    'case.reason_required': 'يرجى تقديم سبب طلب التغيير.',
    'case.rate_placeholder': 'شاركنا تجربتك مع هذه الاستشارة…',
    'case.rating_required': 'يرجى اختيار تقييم بالنجوم قبل الإرسال.',
    'case.thank_you_rating': 'شكراً على ملاحظاتك!',
    'case.mark_completed': 'وضع علامة مكتمل',
    'case.upload_report': 'رفع التقرير',
    'case.upload_recording': 'رفع تسجيل الاجتماع',
    'case.update_status': 'تحديث الحالة',
    'case.update_stage': 'تحديث المرحلة',

    'intake.title': 'استشارة جديدة',
    'intake.goal_label': 'الهدف',
    'intake.goal.living': 'سكن',
    'intake.goal.investment': 'استثمار',
    'intake.goal.resale': 'إعادة بيع',
    'intake.preferred_area': 'المنطقة المفضلة',
    'intake.budget_range': 'نطاق الميزانية',
    'intake.property_type': 'نوع العقار',
    'intake.delivery_time': 'وقت التسليم المفضل',
    'intake.projects': 'مشاريع في البال (اختياري)',
    'intake.notes': 'ملاحظات إضافية',
    'intake.select_consultant': 'اختر مستشاراً (اختياري)',
    'intake.assign_later': 'الإدارة ستعيّن لاحقاً',
    'intake.proceed_to_payment': 'المتابعة للدفع',

    'payment.title': 'الدفع',
    'payment.fee': 'رسوم الاستشارة',
    'payment.secure': 'دفع آمن عبر جيديا',
    'payment.pay_now': 'ادفع الآن',
    'payment.success': 'تم الدفع بنجاح!',
    'payment.failed': 'فشل الدفع. حاول مرة أخرى.',
    'payment.checking': 'جارٍ التحقق من الدفع، يرجى الانتظار…',
    'payment.timeout': 'تعذّر تأكيد الدفع. هل أتممت عملية الدفع؟',
    'payment.check_again': 'لقد دفعت — تحقق مجدداً',
    'payment.cancel': 'إلغاء الدفع',

    'support.title': 'الدعم',
    'support.new_ticket': 'تذكرة جديدة',
    'support.subject': 'الموضوع',
    'support.message': 'الرسالة',
    'support.send': 'إرسال',
    'support.no_tickets': 'لا توجد تذاكر دعم',
    'support.reply': 'رد',
    'support.close_ticket': 'إغلاق التذكرة',
    'support.status.open': 'مفتوحة',
    'support.status.closed': 'مغلقة',
    'support.status.resolved': 'تم الحل',

    'profile.title': 'الملف الشخصي',
    'profile.display_name': 'الاسم',
    'profile.phone': 'رقم الهاتف',
    'profile.location': 'الموقع',
    'profile.save_changes': 'حفظ التغييرات',
    'profile.saved': 'تم تحديث الملف الشخصي!',
    'profile.language': 'اللغة',

    'notifications.title': 'الإشعارات',
    'notifications.empty': 'لا توجد إشعارات',
    'notifications.mark_read': 'وضع كمقروء',

    'admin.staff.title': 'إدارة الموظفين',
    'admin.staff.add': 'إضافة موظف',
    'admin.clients.title': 'إدارة العملاء',
    'admin.assign_consultant': 'تعيين مستشار',
    'admin.assign_quality': 'تعيين أخصائي جودة',
    'admin.reassign_consultant': 'إعادة تعيين المستشار',
    'admin.reassign_quality': 'إعادة تعيين أخصائي الجودة',
    'admin.select_consultant': 'اختر مستشاراً',
    'admin.select_quality': 'اختر أخصائي جودة',
    'admin.pending_reassignment': 'طلب إعادة تعيين معلق',
    'admin.approve': 'موافقة',
    'admin.reject': 'رفض',
    'admin.reassignment_rejected': 'تم رفض طلب إعادة التعيين.',
    'admin.settings': 'الإعدادات',
    'admin.consultation_fee': 'رسوم الاستشارة',
    'admin.export': 'تصدير CSV',
    'admin.mark_paid': 'وضع علامة مدفوع',
    'admin.mark_paid_confirm': 'هل تريد وضع علامة مدفوع على هذه القضية؟ لا يمكن التراجع عن ذلك.',
    'admin.participants': 'المشاركون',
    'admin.client': 'العميل',
    'admin.requested_consultant': 'المستشار المطلوب',
    'admin.none': 'لا يوجد',
    'admin.timeline': 'سجل النشاط',
    'admin.timeline_case_created': 'تم إنشاء القضية',
    'admin.timeline_payment_paid': 'تم استلام الدفع',
    'admin.timeline_payment_pending': 'الدفع معلق',
    'admin.timeline_consultant_assigned': 'تم تعيين المستشار',
    'admin.timeline_quality_assigned': 'تم تعيين أخصائي الجودة',
    'admin.overview': 'نظرة عامة',
    'admin.conversations': 'المحادثات',
    'admin.quality_reports': 'تقارير الجودة',
    'admin.support': 'الدعم',
    'admin.unassigned_cases': 'القضايا غير المعيّنة',
    'admin.active_cases': 'القضايا النشطة',
    'admin.no_unassigned': 'لا توجد قضايا غير معيّنة',
    'admin.no_active': 'لا توجد قضايا نشطة',
    'admin.staff_load': 'حمل الموظفين',
    'admin.active_count': '{count} نشط',
    'admin.monitor': 'مراقبة',
    'admin.deactivate': 'تعطيل',
    'admin.activate': 'تفعيل',
    'admin.deactivate_confirm': 'تعطيل {name}؟ لن يتمكنوا من تسجيل الدخول.',
    'admin.activate_confirm': 'تفعيل {name}؟ سيتمكنون من تسجيل الدخول مجدداً.',
    'admin.cannot_deactivate': 'لا يمكن التعطيل: الموظف لديه قضايا نشطة. أعد تعيينها أولاً.',
    'admin.staff_detail': 'تفاصيل الموظف',
    'admin.cases_assigned': 'القضايا المعيّنة',
    'admin.no_cases_assigned': 'لا توجد قضايا معيّنة',
    'admin.fee_updated': 'تم تحديث الرسوم بنجاح.',
    'admin.clients.total': 'إجمالي العملاء',
    'admin.clients.with_consultations': 'لديهم استشارات',
    'admin.clients.without_consultations': 'بدون استشارات',
    'admin.clients.filter_all': 'الكل',
    'admin.clients.filter_with': 'لديهم استشارات',
    'admin.clients.filter_without': 'بدون استشارات',
    'admin.clients.deactivated': 'معطل',
    'admin.clients.active_count': 'نشط',
    'admin.clients.completed_count': 'مكتمل',
    'admin.staff.filter_all': 'جميع الأدوار',
    'admin.staff.experience': 'الخبرة',
    'admin.staff.years_exp': 'سنوات خبرة',
    'admin.staff.total_consultations': 'المجموع',
    'admin.staff.active_consultations': 'نشط',
    'admin.staff.cases_in_progress': 'قضايا قيد التنفيذ',
    'admin.staff.reassign': 'إعادة تعيين',
    'admin.staff.reassigning': 'جارٍ إعادة التعيين…',
    'admin.staff.no_active_cases': 'لا توجد قضايا نشطة',
    'admin.support.select_ticket': 'اختر تذكرة للعرض',
    'admin.support.reply': 'رد',
    'admin.support.close_ticket': 'إغلاق التذكرة',
    'admin.support.ticket_closed': 'هذه التذكرة مغلقة.',
    'admin.support.send': 'إرسال',
    'admin.support.type_reply': 'اكتب ردك…',
    'admin.support.close_confirm': 'هل تريد إغلاق هذه التذكرة؟',
    'admin.support.closed_by': 'مغلقة',
    'admin.export_consultations': 'تصدير الاستشارات',
    'admin.export_staff': 'تصدير الموظفين',
    'admin.export_quality': 'تصدير تقارير الجودة',
    'admin.export_empty': 'لا توجد بيانات للتصدير.',
    'admin.export_title': 'تصدير التقارير',
    'case.view_chat': 'عرض سجل المحادثة',

    'quality.audit': 'تدقيق الجودة',
    'quality.classification': 'التصنيف',
    'quality.meeting_status': 'حالة الاجتماع',
    'quality.submit_audit': 'إرسال تقرير التدقيق',
    'quality.critical': 'حرج',
    'quality.non_critical': 'غير حرج',
    'quality.recorded': 'مسجل',
    'quality.not_recorded': 'غير مسجل',
    'quality.failed': 'فشل',
    'quality.audit_notes': 'ملاحظات التدقيق',
    'quality.notes_placeholder': 'صف ملاحظات الجودة والمشكلات والتوصيات…',
    'quality.notes_required': 'يرجى إضافة ملاحظات قبل الإرسال.',
    'quality.previous_reports': 'تقارير التدقيق',
    'quality.no_reports': 'لا توجد تقارير تدقيق بعد',
    'quality.report_submitted': 'تم إرسال تقرير التدقيق بنجاح.',

    'consultant.experience': 'سنوات الخبرة',
    'consultant.specialties': 'التخصصات',
    'consultant.completed': 'الاستشارات المكتملة',
    'consultant.bio': 'نبذة',
    'consultant.summary': 'الملخص المهني',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
  isRTL: false,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((stored) => {
      if (stored === 'ar' || stored === 'en') {
        setLanguageState(stored);
        // Ensure RTL state matches the persisted language on cold start
        const shouldBeRTL = stored === 'ar';
        if (I18nManager.isRTL !== shouldBeRTL) {
          I18nManager.forceRTL(shouldBeRTL);
        }
      }
    });
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    AsyncStorage.setItem(STORAGE_KEY, lang);
    // Apply RTL layout direction. I18nManager changes require an app reload
    // to fully re-render the flex layout tree on Android.
    const shouldBeRTL = lang === 'ar';
    if (I18nManager.isRTL !== shouldBeRTL) {
      I18nManager.forceRTL(shouldBeRTL);
      Alert.alert(
        shouldBeRTL ? 'تغيير الاتجاه' : 'Layout Direction Changed',
        shouldBeRTL
          ? 'يرجى إعادة تشغيل التطبيق لتطبيق اتجاه النص العربي.'
          : 'Please restart the app to apply the layout direction change.',
      );
    }
  };

  const t = (key: string, vars?: TranslationVars): string => {
    let value = translations[language][key] || translations.en[key] || key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        value = value.replace(`{${k}}`, String(v ?? ''));
      });
    }
    return value;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL: language === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
